Update TileDB-VCF to 0.34.2
TileDB-Inc/tiledb-vcf-feedstock pull request #137
Opened 2024-08-20 17:45 UTC by awenocur

2024-08-20 17:48 UTC, gspowley approved these changes

2024-08-20 18:12 UTC, jdblischak approved these changes

2024-08-20 18:15 UTC, jdblischak commented
I recommend monitoring the builds post-merge to ensure that new binaries are uploaded. We are short on space on anaconda.org, so the uploads will fail if there isn't sufficient storage (https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/136#issuecomment-2296962325).

2024-08-20 18:15 UTC, jdblischak requested changes
Realized you didn't bump the build number back to `0`

2024-08-20 19:47 UTC, jdblischak approved these changes

2024-08-20 21:03 UTC, merged

2024-08-21 14:15 UTC, jdblischak commented
I confirmed that the [0.34.2 conda binaries](https://anaconda.org/tiledb/libtiledbvcf/files?version=0.34.2) were uploaded